# Generated by Django 3.1.7 on 2021-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.TextField(default='image.png'),
            preserve_default=False,
        ),
    ]
