# Generated by Django 3.1.7 on 2021-07-01 12:39

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210610_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=apps.files.models.file_path),
        ),
    ]
